image: ruby:2.3

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

cache:
  paths: 
    - vendor/

pages:
  stage: deploy
  script:
  - gem install jekyll
  - jekyll build -d public
  - gem build dimension_jekyll_theme.gemspec
  artifacts:
    paths:
    - public